name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - master

jobs:
  trigger-vercel-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧠 Trigger Vercel Deploy Hook
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"